name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINBaYnIlAYNPGJeJ0uFL4+us4/hW0mh5UOcch0+M2ybp kunalshejwal1@gmail.com
          SERVER_USER: Administrator
          SERVER_HOST: http://103.191.208.119/CI_CD_Pipeline/
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
          rsync -avz --delete ./build/ $SERVER_USER@$SERVER_HOST

